### ISSUE TITLE
希望能支持录制twitcasting直播

### ISSUE THREAD

**Issue by brina60602** [ihmily/DouyinLiveRecorder#209]
您好 希望可以将这个直播网站加入录制列表
https://twitcasting.tv
录的时候可以输入cookie登錄
辛苦了

**Comment by Explorare** [comment]
同敲碗，刚想来开个 issue 就看到好哥哥已经提了。目前还能跑的支持 TwitCasting 的录播工具有这两个：
[lovezzzxxx/liverecord: 自动录播并自动备份，支持youtube频道、twitcast频道、twitch频道、openrec频道、niconico生放送、niconico社区、niconico频道、mirrativ频道、reality频道、17live频道、bilibili频道、streamlink支持的直播网址、ffmpeg支持的m3u8地址](https://github.com/lovezzzxxx/liverecord/pulse)
[AlotOfBlahaj/Vtb_Record: A lightweight go program recording streaming of youtube, twitcasting and bilibili](https://github.com/AlotOfBlahaj/Vtb_Record)
都是年久失修，凑合用的。比如vtbRecord 的 cookie 支持写了一半就摸了，我改了改直接把自己的饼干硬编码进去凑合用。

**Comment by ihmily** [comment]
3.0.2版本已支持twitcasting

**Comment by brina60602** [comment]
> 3.0.2版本已支持twitcasting

感谢支持，希望文件名id跟日期中间可以填入当前直播流水号，这样整理档案比较清楚
例如：https://twitcasting.tv/aika_meido/movie/788979996
填入**788979996**变成
天音そら_´꒳`ฅ＠対抗戦ギルドメンバー募集-aika_meido_**788979996**_2024-03-10_01-07-21.ts

或是在[录制设置]修改文件名 是/否 要显示 [主播：]-[id]-[流水号]-[日期].ts   这4种数值

流水号  wss://202-218-143-73.twitcasting.tv/tc.edge/v1/streams/**788979996**.8193.96/fmp4/solid

**Comment by brina60602** [comment]
> 同敲碗，剛想來開個問題就看到好哥哥已經提了。 目前還能運行支援 TwitCasting 的錄播工具有這兩個： [lovezzzxxx/liverecord: 自動錄播並自動備份，支援 youtube 頻道、twitcast頻道、twitch頻道、openrec頻道、niconico生放送、niconico社群、niconico頻道、mirrativ頻道、現實頻道、17live頻道、bilibili頻道、streamlink支援的直播網址、ffmpeg支援的m3u8地址AlotOfBlahaj/Vtb_Record: 一個輕量級的go程式](https://github.com/lovezzzxxx/liverecord/pulse) [錄音串流youtube、twitcasting和bilibili](https://github.com/AlotOfBlahaj/Vtb_Record) 都是年久失修，湊合用的。例如vtbRecord的摸cookie支援寫了一半就了，我改改了直接把自己的餅乾硬編碼進去湊合用。



> 同敲碗，剛想來開個問題就看到好哥哥已經提了。 目前還能運行支援 TwitCasting 的錄播工具有這兩個： [lovezzzxxx/liverecord: 自動錄播並自動備份，支援 youtube 頻道、twitcast頻道、twitch頻道、openrec頻道、niconico生放送、niconico社群、niconico頻道、mirrativ頻道、現實頻道、17live頻道、bilibili頻道、streamlink支援的直播網址、ffmpeg支援的m3u8地址AlotOfBlahaj/Vtb_Record: 一個輕量級的go程式](https://github.com/lovezzzxxx/liverecord/pulse) [錄音串流youtube、twitcasting和bilibili](https://github.com/AlotOfBlahaj/Vtb_Record) 都是年久失修，湊合用的。例如vtbRecord的摸cookie支援寫了一半就了，我改改了直接把自己的餅乾硬編碼進去湊合用。

您好，请教一下vtbRecord填入cookie要怎么修改？想参考一下

**Comment by Explorare** [comment]
> 您好，请教一下vtbRecord填入cookie要怎么修改？想参考一下

@brina60602 我是在最后一步调用 streamlink 的时候把 cookie 硬编码进去的，位置在[这里](https://github.com/AlotOfBlahaj/Vtb_Record/blob/27de4888cb52ca4e754ea09ae99c0231d6834c98/live/videoworker/downloader/provstreamlink/downloadStreamlink.go#L22)，L22 加上 `tc_id` 和 `tc_ss`
```
arg = append(arg, []string{"--http-cookie", "tc_id=<id>", "--http-cookie", "tc_ss=<secret>", "--force", "--output", filepath}...)
```
这个 func 本身是有 cookie string 参数传入的，参数传递如下
[HttpHeaders](https://github.com/AlotOfBlahaj/Vtb_Record/blob/master/live/monitor/base/monitorbase.go#L53)
[HeadersConfig ](https://github.com/AlotOfBlahaj/Vtb_Record/blob/27de4888cb52/live/monitor/base/monitorbase.go#L46)
[func (c *MonitorCtx) GetHeaders() map\[string\]string](https://github.com/Explorare/Vtb_Record/commit/9b5c9fcc1beaccd80e2e34b07404df32ee705bef#diff-c864501ec4ddb09ff0ebad841c1b79b3d9753ff7b2ea880b771ff3e9b7e51987R34)
[cookie = header\["Cookie"\]](https://github.com/AlotOfBlahaj/Vtb_Record/commit/150a1112860abf8ab83ab4136c2d037748206e11#diff-670b46a1462ffc32920ff6328c68bda41d8bf5c1fc9dd00dacda7dc1038e9678R104)
按照设计，这个 cookie 继承自 http-header，这个 header 是用来爬会限内容时候用的，但实际似乎并没有完整实现，脚本并没有从 config.yaml 里读取 header，最后一步调用 streamlink 的时候也没有注入 cookie。我现在实在没精力研究这个了，学了几天 go 也没搞定，希望有大佬能帮忙 fork it。

**Comment by ihmily** [comment]
`我填帐密运行后twitcasting_cookie = 这一行没有出现数值，这样有登陆到吗？`

可以正常录制吗？如果能正常录制可以不用管这个，只有录制的直播间必须要登录时才会去登录获取cookie

**Comment by Explorare** [comment]
我在后台挂了两天之后脚本爆炸了，表现为无法获取数据，登录失败。两天前测试时候是可以正确录制的。目前感觉是这个工具的 UA 被 ban 了？我尝试过用两个账号的 cookie、ID/PW 验证，都过不去，网络走的 TUN 代理，浏览器直接看 TwitCasting 没问题。

```
@explo ➜ DouyinLiveRecorder.v3.0.2  & '.\DouyinLiveRecorder v3.0.2.exe'
-----------------------------------------------------
|                DouyinLiveRecorder                 |
-----------------------------------------------------
版本号: v3.0.2
GitHub: https://github.com/ihmily/DouyinLiveRecorder
支持平台:
国内站点：抖音|快手|虎牙|斗鱼|YY|B站|小红书|bigo直播|blued直播|网易CC|千度热播|猫耳FM|Look直播|TwitCasting
海外站点：TikTok|AfreecaTV|PandaTV|WinkTV|FlexTV|PopkonTV
.....................................................
系统代理检测中，请耐心等待...
已备份配置文件 ./config/config.ini 到 ./backup_config/config.ini_2024-03-12_13-35-05
已备份配置文件 ./config/URL_config.ini 到 ./backup_config/URL_config.ini_2024-03-12_13-35-05
全局/规则网络代理已开启√
运行新线程,传入地址 https://twitcasting.tv/miel_ii
运行新线程,传入地址 https://twitcasting.tv/uununnu
运行新线程,传入地址 https://twitcasting.tv/sena_asumi
运行新线程,传入地址 https://twitcasting.tv/kamito_otaku
运行新线程,传入地址 https://twitcasting.tv/mimi_tosaki
运行新线程,传入地址 https://twitcasting.tv/beni_yakumo
运行新线程,传入地址 https://twitcasting.tv/ema_aizawata
运行新线程,传入地址 https://twitcasting.tv/hinano_tachiba7

运行新线程,传入地址 https://twitcasting.tv/runa_shinomiya
运行新线程,传入地址 https://twitcasting.tv/uruha_ichinose
运行新线程,传入地址 https://twitcasting.tv/merrysan_cas_


运行新线程,传入地址 https://twitcasting.tv/ratna_petit
运行新线程,传入地址 https://twitcasting.tv/mahiroyukishiro
运行新线程,传入地址 https://twitcasting.tv/udukisyuna
运行新线程,传入地址 https://twitcasting.tv/oxonano
运行新线程,传入地址 https://twitcasting.tv/lisa_hanabusa
运行新线程,传入地址 https://twitcasting.tv/boranun2434
运行新线程,传入地址 https://twitcasting.tv/sumire_kaga
运行新线程,传入地址 https://twitcasting.tv/niu_yozuna
获取TwitCasting数据失败，正在尝试登录...
获取TwitCasting数据失败，正在尝试登录...
获取TwitCasting数据失败，正在尝试登录...
获取TwitCasting数据失败，正在尝试登录...
获取TwitCasting数据失败，正在尝试登录...
获取TwitCasting数据失败，正在尝试登录...
2024-03-12 13:35:08.827 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'NoneType' object has no attribute 'group' in function login_twitcasting at line: 1297
2024-03-12 13:35:08.829 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'NoneType' object has no attribute 'group' in function login_twitcasting at line: 1297
2024-03-12 13:35:08.831 | WARNING  | utils:wrapper:18 - 错误信息: type: RuntimeError, TwitCasting登 录失败,请检查配置文件中的账号密码是否正确 in function get_twitcasting_stream_url at line: 1367
2024-03-12 13:35:08.831 | WARNING  | utils:wrapper:18 - 错误信息: type: RuntimeError, TwitCasting登 录失败,请检查配置文件中的账号密码是否正确 in function get_twitcasting_stream_url at line: 1367
2024-03-12 13:35:08.834 | WARNING  | __main__:start_record:1284 - 错误信息: list indices must be integers or slices, not str 发生错误的行数: 928
2024-03-12 13:35:08.835 | WARNING  | __main__:start_record:1284 - 错误信息: list indices must be integers or slices, not str 发生错误的行数: 928
2024-03-12 13:35:09.179 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'NoneType' object has no attribute 'group' in function login_twitcasting at line: 1297
2024-03-12 13:35:09.186 | WARNING  | utils:wrapper:18 - 错误信息: type: RuntimeError, TwitCasting登 录失败,请检查配置文件中的账号密码是否正确 in function get_twitcasting_stream_url at line: 1367
2024-03-12 13:35:09.187 | WARNING  | __main__:start_record:1284 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 907
2024-03-12 13:35:09.187 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'NoneType' object has no attribute 'group' in function login_twitcasting at line: 1297
2024-03-12 13:35:09.373 | WARNING  | utils:wrapper:18 - 错误信息: type: RuntimeError, TwitCasting登 录失败,请检查配置文件中的账号密码是否正确 in function get_twitcasting_stream_url at line: 1367
2024-03-12 13:35:09.374 | WARNING  | __main__:start_record:1284 - 错误信息: list indices must be integers or slices, not str 发生错误的行数: 928
2024-03-12 13:35:09.588 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'NoneType' object has no attribute 'group' in function login_twitcasting at line: 1297
2024-03-12 13:35:09.589 | WARNING  | utils:wrapper:18 - 错误信息: type: RuntimeError, TwitCasting登 录失败,请检查配置文件中的账号密码是否正确 in function get_twitcasting_stream_url at line: 1367
2024-03-12 13:35:09.590 | WARNING  | __main__:start_record:1284 - 错误信息: list indices must be integers or slices, not str 发生错误的行数: 928
2024-03-12 13:35:09.802 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'NoneType' object has no attribute 'group' in function login_twitcasting at line: 1297
获取TwitCasting数据失败，正在尝试登录...
2024-03-12 13:35:09.809 | WARNING  | utils:wrapper:18 - 错误信息: type: RuntimeError, TwitCasting登 录失败,请检查配置文件中的账号密码是否正确 in function get_twitcasting_stream_url at line: 1367
2024-03-12 13:35:09.810 | WARNING  | __main__:start_record:1284 - 错误信息: list indices must be integers or slices, not str 发生错误的行数: 928
获取TwitCasting数据失败，正在尝试登录...
获取TwitCasting数据失败，正在尝试登录...
获取TwitCasting数据失败，正在尝试登录...
获取TwitCasting数据失败，正在尝试登录...
Traceback (most recent call last):
  File "DouyinLiveRecorder\main.py", line 1511, in <module>
  File "DouyinLiveRecorder\main.py", line 1430, in read_config_value
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
  File "<frozen codecs>", line 319, in decode
KeyboardInterrupt
获取TwitCasting数据失败，正在尝试登录...
[8540] Failed to execute script 'main' due to unhandled exception!
```

**Comment by Explorare** [comment]
TwitCasting 录制又开始报错，登录失败。用的主线版本 4dacb92，昨天还正常。

**Comment by alemanmeltondh14-lang** [comment]
TwitCasting多次测试登录不了
