### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by chengsongtaO123** [ihmily/DouyinLiveRecorder#269]
root@racknerd-150230:~/DouyinLiveRecorder# python3 main.py
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    from spider import (
  File "/root/DouyinLiveRecorder/spider.py", line 884, in <module>
    tuple[str, Any]:
TypeError: 'type' object is not subscriptable

**Comment by ihmily** [comment]
该错误已修复 #259
